"""Minor changes

Revision ID: 40998688df2a
Revises: f592678c0723
Create Date: 2018-11-01 16:55:56.958609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40998688df2a'
down_revision = 'f592678c0723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_user_id', sa.Column('req_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_user_id', 'req_complete')
    # ### end Alembic commands ###
