"""empty message

Revision ID: e6c1c82b8780
Revises: 
Create Date: 2018-10-09 18:43:06.378477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c1c82b8780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gram_panchayat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sarpanch_name', sa.String(length=30), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.Column('login', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('no_trips', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('police_station',
    sa.Column('station_no', sa.Integer(), nullable=False),
    sa.Column('officer_name', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('station_no')
    )
    op.create_table('primary_node',
    sa.Column('primary_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.Column('size_field', sa.Float(), nullable=True),
    sa.Column('no_sensors', sa.Integer(), nullable=True),
    sa.Column('no_repair', sa.Integer(), nullable=True),
    sa.Column('no_fines', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('primary_id')
    )
    op.create_table('secondary_node',
    sa.Column('secondary_id', sa.Integer(), nullable=False),
    sa.Column('primary_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('condition', sa.Integer(), nullable=True),
    sa.Column('no_repair', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_id'], ['primary_node.primary_id'], ),
    sa.PrimaryKeyConstraint('secondary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary_node')
    op.drop_table('primary_node')
    op.drop_table('police_station')
    op.drop_table('gram_panchayat')
    # ### end Alembic commands ###
