"""request_harvest added to farmer table

Revision ID: f592678c0723
Revises: f8fe51a9a3c2
Create Date: 2018-10-26 11:24:11.689325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f592678c0723'
down_revision = 'f8fe51a9a3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer', sa.Column('request_harvest', sa.Integer(), nullable=True))
    op.add_column('stalk_collector', sa.Column('district_name', sa.String(length=25), nullable=True))
    op.add_column('stalk_collector', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stalk_collector', 'state')
    op.drop_column('stalk_collector', 'district_name')
    op.drop_column('farmer', 'request_harvest')
    # ### end Alembic commands ###
