"""Initial db

Revision ID: f8fe51a9a3c2
Revises: 
Create Date: 2018-10-25 17:36:44.481931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fe51a9a3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_list',
    sa.Column('job_no', sa.String(length=15), nullable=False),
    sa.Column('date_job', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('collector_id', sa.String(length=20), nullable=True),
    sa.Column('equip_id', sa.String(length=20), nullable=True),
    sa.Column('farmer_id', sa.String(length=20), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('farm_size', sa.Integer(), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('expected_duration', sa.Float(), nullable=True),
    sa.Column('bails_collected', sa.Integer(), nullable=True),
    sa.Column('job_complete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['stalk_collector.collector_id'], ),
    sa.ForeignKeyConstraint(['equip_id'], ['harvest_equipment.equip_id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request_harvest.request_id'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_list')
    # ### end Alembic commands ###
